[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
log = "0.4.25"
three-d = { version ="*", features= ["egui-gui", "text"] }
solvers = { path = "../solvers" }
