[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_commonmark = "0.19"
image = { version = "*", default-features = false, features = ["png"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
log = "0.4.25"
rand = "0.9"
solvers = { path = "../solvers" }
three-d = { version = "0.30", features= ["egui-gui", "text"] }
